[brew] deal with xcode inital requirement debacle...
is the requirement for full xcode just for macvim build?

here we try to loudly ensure you have some kind of xcode before we'll
run, and we quietly try and accept its license either way (as its a
silent  no op if license is already accepted)

A requirement for the license was sudo, which actually the rest of the
script was crying out for since we randomly get asked for sudo about 4
times during the installations. Copied the nice sudo persister from the
macos script

diff --git a/1_brew_cask_installer_script b/1_brew_cask_installer_script
--- a/1_brew_cask_installer_script
+++ b/1_brew_cask_installer_script
@@ -1,6 +1,21 @@
 #! /bin/bash
 # Functions as a Homebrew and Homebrew/Cask setup script, as a running binary or app install script and as a running update/upgrade script for all of those
 
+# Ask for the administrator password upfront
+sudo -v
+
+# Keep-alive: update existing `sudo` time stamp until this script has finished
+while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+
+# because of something silly,  we need full xcode for macvim build - stackoverflow.com/a/15371967/3536094 - return value will be 2 if NOT exist, 0 if exist
+xcode-select -p 1>/dev/null; if (( $? == 2 )); then 
+ echo "Full XCode (with license accepted) recommended (for eg: macvim install). Exiting until its found (otherwise brew will install command line tools). Go install from the app store"
+ exit 1
+fi
+# now lets silently accept the xcode license in case its a first run - https://stackoverflow.com/questions/58632629/how-to-check-if-xcode-license-needs-to-be-accepted
+echo "xcode license may need accepting, silently taking care of that..."
+sudo xcodebuild -license accept &>/dev/null
+
 echo "Checking for Homebrew and installing if we don't have it"
 if test ! $(which brew); then
   echo "Installing homebrew..."
